export const primaryColor = '#673ab7'
export const primaryColorFocused = '#512da8'
export const textInPrimary = 'white'
export const secondaryColor = '#ffff00'
export const secondaryColorFocused = '#ffea00'
export const textInSecondary = 'black'
export const fontFamily = 'Roboto'
